name = "mystdlib"
version = "0.1.0"
defaultTargets = ["mystdlib"]

[[lean_lib]]
name = "Mystdlib"

# [[require]]
# name = "mathlib"
# git = "https://github.com/leanprover-community/mathlib4-nightly-testing"
# rev = "8cc4b4c075883b8f26f81031159c19bb6505ef23"

[[require]]
name = "cslib"
scope = "leanprover"
rev = "b31f311ccff29c68ce4146f2bed46fa446870dba"


